### ISSUE TITLE
Stworzenie grafik - plansza + statki + przyciski + logo

### ISSUE THREAD

**Issue by jaqubm** [jaqubm/Battleship_4x4#2]
Elementy do wykonanie:

- [x] logo gry
- [x] grafika przycisku
- [x] statki o długościach odpowiednio - 2, 3, 4 oraz 5 pól
- [x] plansza gry
- [x] animowana część planszy - jedno pole wody
- [x] animacja eksplozji
- [x] tabela wyników

**Comment by SebixR** [comment]
![Image](https://github.com/jaqubm/Battleship_4x4/assets/97166706/6eee5858-7fd4-4ec2-94ac-532a01a29a46)

**Comment by SebixR** [comment]
![Image](https://github.com/jaqubm/Battleship_4x4/assets/97166706/9a6695d4-3b6d-49f6-a28c-859dff0917ae)

**Comment by SebixR** [comment]
![Image](https://github.com/jaqubm/Battleship_4x4/assets/97166706/da54e0fe-3167-4d5b-a2cb-37ef78c00794)

**Comment by SebixR** [comment]
![Image](https://github.com/jaqubm/Battleship_4x4/assets/97166706/e85a2d4f-f4fc-4640-acb6-242d6b663fd4)

**Comment by SebixR** [comment]
![Image](https://github.com/jaqubm/Battleship_4x4/assets/97166706/5defc0d0-23f8-4b32-b6d5-3a2af50d98af)
